//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bestchat
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conferences
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Conferences()
        {
            this.ConferenceChat = new HashSet<ConferenceChat>();
        }
    
        public int Id { get; set; }
        public string ConferenceRoomName { get; set; }
        public string owner { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConferenceChat> ConferenceChat { get; set; }
    }
}
