//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bestchat
{
    using System;
    using System.Collections.Generic;
    
    public partial class friends
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int FriendId { get; set; }
        public Nullable<bool> Accept { get; set; }
        public Nullable<int> chatCount { get; set; }
    
        public virtual user user { get; set; }
    }
}
