//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bestchat
{
    using System;
    using System.Collections.Generic;
    
    public partial class Limits
    {
        public int id { get; set; }
        public string cpuId { get; set; }
        public Nullable<int> userLimit { get; set; }
        public Nullable<int> emailLimit { get; set; }
    }
}
