//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bestchat
{
    using System;
    using System.Collections.Generic;
    
    public partial class Machin
    {
        public string CpuID { get; set; }
        public Nullable<System.DateTime> WarningDate { get; set; }
        public Nullable<int> WarningCount { get; set; }
    }
}
