//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bestchat
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class amirabbasi1Entities1 : DbContext
    {
        public amirabbasi1Entities1()
            : base("name=amirabbasi1Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<chat> chat { get; set; }
        public virtual DbSet<cities> cities { get; set; }
        public virtual DbSet<ConferenceChat> ConferenceChat { get; set; }
        public virtual DbSet<Conferences> Conferences { get; set; }
        public virtual DbSet<countries> countries { get; set; }
        public virtual DbSet<declined> declined { get; set; }
        public virtual DbSet<friends> friends { get; set; }
        public virtual DbSet<Immoral> Immoral { get; set; }
        public virtual DbSet<invited> invited { get; set; }
        public virtual DbSet<Likes> Likes { get; set; }
        public virtual DbSet<Limits> Limits { get; set; }
        public virtual DbSet<Machin> Machin { get; set; }
        public virtual DbSet<posts> posts { get; set; }
        public virtual DbSet<@private> @private { get; set; }
        public virtual DbSet<room> room { get; set; }
        public virtual DbSet<states> states { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<unImmoral> unImmoral { get; set; }
        public virtual DbSet<unImmoralReport> unImmoralReport { get; set; }
        public virtual DbSet<user> user { get; set; }
        public virtual DbSet<CrashReport> CrashReport { get; set; }
        public virtual DbSet<version> version { get; set; }
        public virtual DbSet<ConfrenceUsers> ConfrenceUsers { get; set; }
    }
}
